#[[main]]
  name = "Work"
  pageRef = "work"
  weight = 10

[[main]]
  name = "Services"
  pageRef = "services"
  weight = 20

[[footer]]
  name = "Work"
  pageRef = "work"
  weight = 10

[[footer]]
  name = "Services"
  pageRef = "services"
  weight = 20