[[main]]
  name = "Work"
  url = "/work/"
  weight = 10

[[main]]
  name = "Services"
  url = "/services/"
  weight = 20

[[footer]]
  name = "Work"
  url = "/work/"
  weight = 10

[[footer]]
  name = "Services"
  url = "/services/"
  weight = 20